### ISSUE TITLE
rv_histogram behaves weird on build/hello.elf

### ISSUE THREAD

**Issue by ChinYikMing** [sysprog21/rv32emu#191] opened 2023-08-14 08:10 UTC
The second `unknown` is weird
```
+---------------------------------------------+
| RV32 Target Instruction Frequency Histogram |
+---------------------------------------------+
  1. addi       0.50% [9         ] ***************************************************************************************************************************
  2. unknown    0.28% [5         ] ********************************************************************
  3. jal        0.17% [3         ] *****************************************
  4. ecall      0.11% [2         ] ***************************
  5. nop        0.06% [1         ] *************
  6. auipc      0.06% [1         ] *************
  7. beq        0.06% [1         ] *************
  8. cnop       0.06% [1         ] *************
  9. lui        0.00% [0         ] 
 10. jalr       0.00% [0         ] 
 ...
123. cjalr      0.00% [0         ] 
124. cadd       0.00% [0         ] 
125. cswsp      0.00% [0         ] 
```
_Originally posted by @jserv in https://github.com/sysprog21/rv32emu/issues/187#issuecomment-1676196422_

**Comment by gagachang** [comment] 2023-08-28 07:48
It seems the root cause is that `"Hello World!\n"`  is mixed with the `.text` section (starts from address 0x40 in disassembly):

```C
Disassembly of section .text:

00000000 <_start>:
   0:	00000293          	li	t0,0
   4:	00500313          	li	t1,5
   8:	0040006f          	j	0xc <_start+0xc>
   c:	00000013          	nop

......

00000040 <str>:
  40:	6c6c6548          	.word	0x6c6c6548
  44:	6f57206f          	.word	0x6f57206f
  48:	21646c72          	.word	0x21646c72
  4c:	0000000a          	.word	0x0000000a
```

The `rv_histogram`  decodes the `.text` section, which includes `"Hello World!\n"`.
Therefore the decoder returns unknown instruction.

Issue can be fixed by putting `"Hello World!\n"` into other sections (e.g., rodata):

```diff
diff --git a/tests/asm-hello/hello.S b/tests/asm-hello/hello.S
index 8941a6d..fa72e69 100644
--- a/tests/asm-hello/hello.S
+++ b/tests/asm-hello/hello.S
@@ -8,7 +8,7 @@
 .set SYSEXIT,  93
 .set SYSWRITE, 64
 
-.data
+.section .rodata
 str: .ascii "Hello World!\n"
      .set str_size, .-str
```

The analysis on `build/hello.elf` is correct:
```
+---------------------------------------------+
| RV32 Target Instruction Frequency Histogram |
+---------------------------------------------+
  1. addi      60.00% [9         ] ██████████████████████████████████████████████████████████████████████████████████████████████████████████
  2. jal       13.33% [2         ] ███████████████████████▌
  3. ecall     13.33% [2         ] ███████████████████████▌
  4. nop        6.67% [1         ] ███████████▊
  5. beq        6.67% [1         ] ███████████▊
```

**Comment by jserv** [comment] 2023-08-28 08:47
@gagachang, can you send a pull request? So that, @qwe661234 and I can confirm later.

**Comment by gagachang** [comment] 2023-08-28 09:32
Please see https://github.com/sysprog21/rv32emu/pull/199

**Closed as completed** 2023-08-28 12:22 UTC
